# Generated by hand for AQI pipeline initial schema

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AQIStation",
            fields=[
                ("station_id", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, spatial_index=True, srid=4326
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "aqi_station"},
        ),
        migrations.CreateModel(
            name="AQIStationSnapshot",
            fields=[
                (
                    "station",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="snapshot",
                        serialize=False,
                        to="django_app.aqistation",
                    ),
                ),
                (
                    "aqi",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(500),
                        ]
                    ),
                ),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("fetched_at", models.DateTimeField()),
                ("source_payload_hash", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "aqi_station_snapshot",
                "indexes": [models.Index(fields=["observed_at"], name="aqi_snapshot_observed_idx")],
            },
        ),
    ]
